graph TD
    lodash --> async
    lodash --> benchmark
    lodash --> chalk
    lodash --> cheerio
    lodash --> codecov.io
    lodash --> coveralls
    lodash --> curl-amd
    lodash --> docdown
    lodash --> dojo
    lodash --> ecstatic
    lodash --> fs-extra
    lodash --> glob
    lodash --> istanbul
    lodash --> jquery
    lodash --> jscs
    lodash --> lodash
    lodash --> lodash-doc-globals
    lodash --> markdown-doctest
    lodash --> optional-dev-dependency
    lodash --> platform
    lodash --> qunit-extras
    lodash --> qunitjs
    lodash --> request
    lodash --> requirejs
    lodash --> sauce-tunnel
    lodash --> uglify-js
    lodash --> webpack
    async --> lodash
    benchmark --> lodash
    benchmark --> platform
    chalk --> ansi-styles
    chalk --> escape-string-regexp
    chalk --> has-ansi
    chalk --> strip-ansi
    chalk --> supports-color
    has-ansi --> ansi-regex
    strip-ansi --> ansi-regex
    cheerio --> css-select
    cheerio --> dom-serializer
    cheerio --> entities
    cheerio --> htmlparser2
    cheerio --> lodash.assignin
    cheerio --> lodash.bind
    cheerio --> lodash.defaults
    cheerio --> lodash.filter
    cheerio --> lodash.flatten
    cheerio --> lodash.foreach
    cheerio --> lodash.map
    cheerio --> lodash.merge
    cheerio --> lodash.pick
    cheerio --> lodash.reduce
    cheerio --> lodash.reject
    cheerio --> lodash.some
    css-select --> boolbase
    css-select --> css-what
    css-select --> domutils
    css-select --> nth-check
    domutils --> dom-serializer
    domutils --> domelementtype
    dom-serializer --> domelementtype
    dom-serializer --> entities
    nth-check --> boolbase
    htmlparser2 --> domelementtype
    htmlparser2 --> domhandler
    htmlparser2 --> domutils
    htmlparser2 --> entities
    htmlparser2 --> inherits
    htmlparser2 --> readable-stream
    domhandler --> domelementtype
    readable-stream --> core-util-is
    readable-stream --> inherits
    readable-stream --> isarray
    readable-stream --> process-nextick-args
    readable-stream --> safe-buffer
    readable-stream --> string_decoder
    readable-stream --> util-deprecate
    string_decoder --> safe-buffer
    codecov.io --> request
    codecov.io --> urlgrey
    request --> aws-sign2
    request --> aws4
    request --> caseless
    request --> combined-stream
    request --> extend
    request --> forever-agent
    request --> form-data
    request --> har-validator
    request --> http-signature
    request --> is-typedarray
    request --> isstream
    request --> json-stringify-safe
    request --> mime-types
    request --> oauth-sign
    request --> performance-now
    request --> qs
    request --> safe-buffer
    request --> tough-cookie
    request --> tunnel-agent
    request --> uuid
    combined-stream --> delayed-stream
    form-data --> async
    form-data --> combined-stream
    form-data --> mime
    har-validator --> chalk
    har-validator --> commander
    har-validator --> is-my-json-valid
    har-validator --> pinkie-promise
    is-my-json-valid --> generate-function
    is-my-json-valid --> generate-object-property
    is-my-json-valid --> is-my-ip-valid
    is-my-json-valid --> jsonpointer
    is-my-json-valid --> xtend
    generate-object-property --> is-property
    pinkie-promise --> pinkie
    http-signature --> asn1
    http-signature --> assert-plus
    http-signature --> ctype
    tough-cookie --> punycode
    urlgrey --> tape
    tape --> deep-equal
    tape --> defined
    tape --> inherits
    tape --> jsonify
    tape --> resumer
    tape --> split
    tape --> stream-combiner
    tape --> through
    resumer --> through
    split --> through
    stream-combiner --> duplexer
    coveralls --> js-yaml
    coveralls --> lcov-parse
    coveralls --> log-driver
    coveralls --> minimist
    coveralls --> request
    js-yaml --> argparse
    js-yaml --> esprima
    argparse --> sprintf-js
    docdown --> doctrine
    docdown --> lodash
    doctrine --> esutils
    doctrine --> isarray
    ecstatic --> he
    ecstatic --> mime
    ecstatic --> minimist
    ecstatic --> url-join
    fs-extra --> graceful-fs
    fs-extra --> jsonfile
    fs-extra --> klaw
    glob --> fs.realpath
    glob --> inflight
    glob --> inherits
    glob --> minimatch
    glob --> once
    glob --> path-is-absolute
    inflight --> once
    inflight --> wrappy
    once --> wrappy
    minimatch --> brace-expansion
    brace-expansion --> balanced-match
    brace-expansion --> concat-map
    istanbul --> abbrev
    istanbul --> async
    istanbul --> escodegen
    istanbul --> esprima
    istanbul --> glob
    istanbul --> handlebars
    istanbul --> js-yaml
    istanbul --> mkdirp
    istanbul --> nopt
    istanbul --> once
    istanbul --> resolve
    istanbul --> supports-color
    istanbul --> which
    istanbul --> wordwrap
    escodegen --> esprima
    escodegen --> estraverse
    escodegen --> esutils
    escodegen --> optionator
    optionator --> deep-is
    optionator --> fast-levenshtein
    optionator --> levn
    optionator --> prelude-ls
    optionator --> type-check
    optionator --> wordwrap
    levn --> prelude-ls
    levn --> type-check
    type-check --> prelude-ls
    handlebars --> neo-async
    handlebars --> optimist
    handlebars --> source-map
    optimist --> minimist
    optimist --> wordwrap
    source-map --> amdefine
    mkdirp --> minimist
    nopt --> abbrev
    which --> isexe
    jscs --> chalk
    jscs --> cli-table
    jscs --> commander
    jscs --> cst
    jscs --> estraverse
    jscs --> exit
    jscs --> glob
    jscs --> htmlparser2
    jscs --> js-yaml
    jscs --> jscs-jsdoc
    jscs --> jscs-preset-wikimedia
    jscs --> jsonlint
    jscs --> lodash
    jscs --> minimatch
    jscs --> natural-compare
    jscs --> pathval
    jscs --> prompt
    jscs --> reserved-words
    jscs --> resolve
    jscs --> strip-bom
    jscs --> strip-json-comments
    jscs --> to-double-quotes
    jscs --> to-single-quotes
    jscs --> vow
    jscs --> vow-fs
    jscs --> xmlbuilder
    cli-table --> colors
    cst --> babel-runtime
    cst --> babylon
    cst --> source-map-support
    babel-runtime --> core-js
    babel-runtime --> regenerator-runtime
    source-map-support --> source-map
    jscs-jsdoc --> comment-parser
    jscs-jsdoc --> jsdoctypeparser
    comment-parser --> readable-stream
    jsdoctypeparser --> lodash
    jsonlint --> JSV
    jsonlint --> nomnom
    nomnom --> chalk
    nomnom --> underscore
    prompt --> pkginfo
    prompt --> read
    prompt --> revalidator
    prompt --> utile
    prompt --> winston
    read --> mute-stream
    utile --> async
    utile --> deep-equal
    utile --> i
    utile --> mkdirp
    utile --> ncp
    utile --> rimraf
    rimraf --> glob
    winston --> async
    winston --> colors
    winston --> cycle
    winston --> eyes
    winston --> isstream
    winston --> pkginfo
    winston --> stack-trace
    strip-bom --> is-utf8
    vow-fs --> glob
    vow-fs --> uuid
    vow-fs --> vow
    vow-fs --> vow-queue
    vow-queue --> vow
    xmlbuilder --> lodash
    lodash-doc-globals --> lodash
    markdown-doctest --> babel-core
    markdown-doctest --> babel-preset-es2015
    markdown-doctest --> babel-preset-stage-0
    markdown-doctest --> chalk
    markdown-doctest --> glob
    markdown-doctest --> istanbul
    babel-core --> babel-code-frame
    babel-core --> babel-generator
    babel-core --> babel-helpers
    babel-core --> babel-messages
    babel-core --> babel-register
    babel-core --> babel-runtime
    babel-core --> babel-template
    babel-core --> babel-traverse
    babel-core --> babel-types
    babel-core --> babylon
    babel-core --> convert-source-map
    babel-core --> debug
    babel-core --> json5
    babel-core --> lodash
    babel-core --> minimatch
    babel-core --> path-is-absolute
    babel-core --> private
    babel-core --> slash
    babel-core --> source-map
    babel-code-frame --> chalk
    babel-code-frame --> esutils
    babel-code-frame --> js-tokens
    babel-generator --> babel-messages
    babel-generator --> babel-runtime
    babel-generator --> babel-types
    babel-generator --> detect-indent
    babel-generator --> jsesc
    babel-generator --> lodash
    babel-generator --> source-map
    babel-generator --> trim-right
    babel-messages --> babel-runtime
    babel-types --> babel-runtime
    babel-types --> esutils
    babel-types --> lodash
    babel-types --> to-fast-properties
    detect-indent --> repeating
    repeating --> is-finite
    is-finite --> number-is-nan
    babel-helpers --> babel-runtime
    babel-helpers --> babel-template
    babel-template --> babel-runtime
    babel-template --> babel-traverse
    babel-template --> babel-types
    babel-template --> babylon
    babel-template --> lodash
    babel-traverse --> babel-code-frame
    babel-traverse --> babel-messages
    babel-traverse --> babel-runtime
    babel-traverse --> babel-types
    babel-traverse --> babylon
    babel-traverse --> debug
    babel-traverse --> globals
    babel-traverse --> invariant
    babel-traverse --> lodash
    debug --> ms
    invariant --> loose-envify
    loose-envify --> js-tokens
    babel-register --> babel-core
    babel-register --> babel-runtime
    babel-register --> core-js
    babel-register --> home-or-tmp
    babel-register --> lodash
    babel-register --> mkdirp
    babel-register --> source-map-support
    home-or-tmp --> os-homedir
    home-or-tmp --> os-tmpdir
    babel-preset-es2015 --> babel-plugin-check-es2015-constants
    babel-preset-es2015 --> babel-plugin-transform-es2015-arrow-functions
    babel-preset-es2015 --> babel-plugin-transform-es2015-block-scoped-functions
    babel-preset-es2015 --> babel-plugin-transform-es2015-block-scoping
    babel-preset-es2015 --> babel-plugin-transform-es2015-classes
    babel-preset-es2015 --> babel-plugin-transform-es2015-computed-properties
    babel-preset-es2015 --> babel-plugin-transform-es2015-destructuring
    babel-preset-es2015 --> babel-plugin-transform-es2015-duplicate-keys
    babel-preset-es2015 --> babel-plugin-transform-es2015-for-of
    babel-preset-es2015 --> babel-plugin-transform-es2015-function-name
    babel-preset-es2015 --> babel-plugin-transform-es2015-literals
    babel-preset-es2015 --> babel-plugin-transform-es2015-modules-amd
    babel-preset-es2015 --> babel-plugin-transform-es2015-modules-commonjs
    babel-preset-es2015 --> babel-plugin-transform-es2015-modules-systemjs
    babel-preset-es2015 --> babel-plugin-transform-es2015-modules-umd
    babel-preset-es2015 --> babel-plugin-transform-es2015-object-super
    babel-preset-es2015 --> babel-plugin-transform-es2015-parameters
    babel-preset-es2015 --> babel-plugin-transform-es2015-shorthand-properties
    babel-preset-es2015 --> babel-plugin-transform-es2015-spread
    babel-preset-es2015 --> babel-plugin-transform-es2015-sticky-regex
    babel-preset-es2015 --> babel-plugin-transform-es2015-template-literals
    babel-preset-es2015 --> babel-plugin-transform-es2015-typeof-symbol
    babel-preset-es2015 --> babel-plugin-transform-es2015-unicode-regex
    babel-preset-es2015 --> babel-plugin-transform-regenerator
    babel-plugin-check-es2015-constants --> babel-runtime
    babel-plugin-transform-es2015-arrow-functions --> babel-runtime
    babel-plugin-transform-es2015-block-scoped-functions --> babel-runtime
    babel-plugin-transform-es2015-block-scoping --> babel-runtime
    babel-plugin-transform-es2015-block-scoping --> babel-template
    babel-plugin-transform-es2015-block-scoping --> babel-traverse
    babel-plugin-transform-es2015-block-scoping --> babel-types
    babel-plugin-transform-es2015-block-scoping --> lodash
    babel-plugin-transform-es2015-classes --> babel-helper-define-map
    babel-plugin-transform-es2015-classes --> babel-helper-function-name
    babel-plugin-transform-es2015-classes --> babel-helper-optimise-call-expression
    babel-plugin-transform-es2015-classes --> babel-helper-replace-supers
    babel-plugin-transform-es2015-classes --> babel-messages
    babel-plugin-transform-es2015-classes --> babel-runtime
    babel-plugin-transform-es2015-classes --> babel-template
    babel-plugin-transform-es2015-classes --> babel-traverse
    babel-plugin-transform-es2015-classes --> babel-types
    babel-helper-define-map --> babel-helper-function-name
    babel-helper-define-map --> babel-runtime
    babel-helper-define-map --> babel-types
    babel-helper-define-map --> lodash
    babel-helper-function-name --> babel-helper-get-function-arity
    babel-helper-function-name --> babel-runtime
    babel-helper-function-name --> babel-template
    babel-helper-function-name --> babel-traverse
    babel-helper-function-name --> babel-types
    babel-helper-get-function-arity --> babel-runtime
    babel-helper-get-function-arity --> babel-types
    babel-helper-optimise-call-expression --> babel-runtime
    babel-helper-optimise-call-expression --> babel-types
    babel-helper-replace-supers --> babel-helper-optimise-call-expression
    babel-helper-replace-supers --> babel-messages
    babel-helper-replace-supers --> babel-runtime
    babel-helper-replace-supers --> babel-template
    babel-helper-replace-supers --> babel-traverse
    babel-helper-replace-supers --> babel-types
    babel-plugin-transform-es2015-computed-properties --> babel-runtime
    babel-plugin-transform-es2015-computed-properties --> babel-template
    babel-plugin-transform-es2015-destructuring --> babel-runtime
    babel-plugin-transform-es2015-duplicate-keys --> babel-runtime
    babel-plugin-transform-es2015-duplicate-keys --> babel-types
    babel-plugin-transform-es2015-for-of --> babel-runtime
    babel-plugin-transform-es2015-function-name --> babel-helper-function-name
    babel-plugin-transform-es2015-function-name --> babel-runtime
    babel-plugin-transform-es2015-function-name --> babel-types
    babel-plugin-transform-es2015-literals --> babel-runtime
    babel-plugin-transform-es2015-modules-amd --> babel-plugin-transform-es2015-modules-commonjs
    babel-plugin-transform-es2015-modules-amd --> babel-runtime
    babel-plugin-transform-es2015-modules-amd --> babel-template
    babel-plugin-transform-es2015-modules-commonjs --> babel-plugin-transform-strict-mode
    babel-plugin-transform-es2015-modules-commonjs --> babel-runtime
    babel-plugin-transform-es2015-modules-commonjs --> babel-template
    babel-plugin-transform-es2015-modules-commonjs --> babel-types
    babel-plugin-transform-strict-mode --> babel-runtime
    babel-plugin-transform-strict-mode --> babel-types
    babel-plugin-transform-es2015-modules-systemjs --> babel-helper-hoist-variables
    babel-plugin-transform-es2015-modules-systemjs --> babel-runtime
    babel-plugin-transform-es2015-modules-systemjs --> babel-template
    babel-helper-hoist-variables --> babel-runtime
    babel-helper-hoist-variables --> babel-types
    babel-plugin-transform-es2015-modules-umd --> babel-plugin-transform-es2015-modules-amd
    babel-plugin-transform-es2015-modules-umd --> babel-runtime
    babel-plugin-transform-es2015-modules-umd --> babel-template
    babel-plugin-transform-es2015-object-super --> babel-helper-replace-supers
    babel-plugin-transform-es2015-object-super --> babel-runtime
    babel-plugin-transform-es2015-parameters --> babel-helper-call-delegate
    babel-plugin-transform-es2015-parameters --> babel-helper-get-function-arity
    babel-plugin-transform-es2015-parameters --> babel-runtime
    babel-plugin-transform-es2015-parameters --> babel-template
    babel-plugin-transform-es2015-parameters --> babel-traverse
    babel-plugin-transform-es2015-parameters --> babel-types
    babel-helper-call-delegate --> babel-helper-hoist-variables
    babel-helper-call-delegate --> babel-runtime
    babel-helper-call-delegate --> babel-traverse
    babel-helper-call-delegate --> babel-types
    babel-plugin-transform-es2015-shorthand-properties --> babel-runtime
    babel-plugin-transform-es2015-shorthand-properties --> babel-types
    babel-plugin-transform-es2015-spread --> babel-runtime
    babel-plugin-transform-es2015-sticky-regex --> babel-helper-regex
    babel-plugin-transform-es2015-sticky-regex --> babel-runtime
    babel-plugin-transform-es2015-sticky-regex --> babel-types
    babel-helper-regex --> babel-runtime
    babel-helper-regex --> babel-types
    babel-helper-regex --> lodash
    babel-plugin-transform-es2015-template-literals --> babel-runtime
    babel-plugin-transform-es2015-typeof-symbol --> babel-runtime
    babel-plugin-transform-es2015-unicode-regex --> babel-helper-regex
    babel-plugin-transform-es2015-unicode-regex --> babel-runtime
    babel-plugin-transform-es2015-unicode-regex --> regexpu-core
    regexpu-core --> regenerate
    regexpu-core --> regjsgen
    regexpu-core --> regjsparser
    regjsparser --> jsesc
    babel-plugin-transform-regenerator --> regenerator-transform
    regenerator-transform --> babel-runtime
    regenerator-transform --> babel-types
    regenerator-transform --> private
    babel-preset-stage-0 --> babel-plugin-transform-do-expressions
    babel-preset-stage-0 --> babel-plugin-transform-function-bind
    babel-preset-stage-0 --> babel-preset-stage-1
    babel-plugin-transform-do-expressions --> babel-plugin-syntax-do-expressions
    babel-plugin-transform-do-expressions --> babel-runtime
    babel-plugin-transform-function-bind --> babel-plugin-syntax-function-bind
    babel-plugin-transform-function-bind --> babel-runtime
    babel-preset-stage-1 --> babel-plugin-transform-class-constructor-call
    babel-preset-stage-1 --> babel-plugin-transform-export-extensions
    babel-preset-stage-1 --> babel-preset-stage-2
    babel-plugin-transform-class-constructor-call --> babel-plugin-syntax-class-constructor-call
    babel-plugin-transform-class-constructor-call --> babel-runtime
    babel-plugin-transform-class-constructor-call --> babel-template
    babel-plugin-transform-export-extensions --> babel-plugin-syntax-export-extensions
    babel-plugin-transform-export-extensions --> babel-runtime
    babel-preset-stage-2 --> babel-plugin-syntax-dynamic-import
    babel-preset-stage-2 --> babel-plugin-transform-class-properties
    babel-preset-stage-2 --> babel-plugin-transform-decorators
    babel-preset-stage-2 --> babel-preset-stage-3
    babel-plugin-transform-class-properties --> babel-helper-function-name
    babel-plugin-transform-class-properties --> babel-plugin-syntax-class-properties
    babel-plugin-transform-class-properties --> babel-runtime
    babel-plugin-transform-class-properties --> babel-template
    babel-plugin-transform-decorators --> babel-helper-explode-class
    babel-plugin-transform-decorators --> babel-plugin-syntax-decorators
    babel-plugin-transform-decorators --> babel-runtime
    babel-plugin-transform-decorators --> babel-template
    babel-plugin-transform-decorators --> babel-types
    babel-helper-explode-class --> babel-helper-bindify-decorators
    babel-helper-explode-class --> babel-runtime
    babel-helper-explode-class --> babel-traverse
    babel-helper-explode-class --> babel-types
    babel-helper-bindify-decorators --> babel-runtime
    babel-helper-bindify-decorators --> babel-traverse
    babel-helper-bindify-decorators --> babel-types
    babel-preset-stage-3 --> babel-plugin-syntax-trailing-function-commas
    babel-preset-stage-3 --> babel-plugin-transform-async-generator-functions
    babel-preset-stage-3 --> babel-plugin-transform-async-to-generator
    babel-preset-stage-3 --> babel-plugin-transform-exponentiation-operator
    babel-preset-stage-3 --> babel-plugin-transform-object-rest-spread
    babel-plugin-transform-async-generator-functions --> babel-helper-remap-async-to-generator
    babel-plugin-transform-async-generator-functions --> babel-plugin-syntax-async-generators
    babel-plugin-transform-async-generator-functions --> babel-runtime
    babel-helper-remap-async-to-generator --> babel-helper-function-name
    babel-helper-remap-async-to-generator --> babel-runtime
    babel-helper-remap-async-to-generator --> babel-template
    babel-helper-remap-async-to-generator --> babel-traverse
    babel-helper-remap-async-to-generator --> babel-types
    babel-plugin-transform-async-to-generator --> babel-helper-remap-async-to-generator
    babel-plugin-transform-async-to-generator --> babel-plugin-syntax-async-functions
    babel-plugin-transform-async-to-generator --> babel-runtime
    babel-plugin-transform-exponentiation-operator --> babel-helper-builder-binary-assignment-operator-visitor
    babel-plugin-transform-exponentiation-operator --> babel-plugin-syntax-exponentiation-operator
    babel-plugin-transform-exponentiation-operator --> babel-runtime
    babel-helper-builder-binary-assignment-operator-visitor --> babel-helper-explode-assignable-expression
    babel-helper-builder-binary-assignment-operator-visitor --> babel-runtime
    babel-helper-builder-binary-assignment-operator-visitor --> babel-types
    babel-helper-explode-assignable-expression --> babel-runtime
    babel-helper-explode-assignable-expression --> babel-traverse
    babel-helper-explode-assignable-expression --> babel-types
    babel-plugin-transform-object-rest-spread --> babel-plugin-syntax-object-rest-spread
    babel-plugin-transform-object-rest-spread --> babel-runtime
    optional-dev-dependency --> async
    optional-dev-dependency --> cross-spawn
    optional-dev-dependency --> lodash.assign
    optional-dev-dependency --> yargs
    cross-spawn --> lru-cache
    cross-spawn --> shebang-command
    cross-spawn --> which
    lru-cache --> pseudomap
    lru-cache --> yallist
    shebang-command --> shebang-regex
    yargs --> camelcase
    yargs --> cliui
    yargs --> decamelize
    yargs --> window-size
    cliui --> center-align
    cliui --> right-align
    cliui --> wordwrap
    center-align --> align-text
    center-align --> lazy-cache
    align-text --> kind-of
    align-text --> longest
    align-text --> repeat-string
    kind-of --> is-buffer
    right-align --> align-text
    qunitjs --> chokidar
    qunitjs --> commander
    qunitjs --> exists-stat
    qunitjs --> findup-sync
    qunitjs --> js-reporters
    qunitjs --> resolve
    qunitjs --> walk-sync
    chokidar --> anymatch
    chokidar --> async-each
    chokidar --> glob-parent
    chokidar --> inherits
    chokidar --> is-binary-path
    chokidar --> is-glob
    chokidar --> path-is-absolute
    chokidar --> readdirp
    anymatch --> micromatch
    anymatch --> normalize-path
    micromatch --> arr-diff
    micromatch --> array-unique
    micromatch --> braces
    micromatch --> expand-brackets
    micromatch --> extglob
    micromatch --> filename-regex
    micromatch --> is-extglob
    micromatch --> is-glob
    micromatch --> kind-of
    micromatch --> normalize-path
    micromatch --> object.omit
    micromatch --> parse-glob
    micromatch --> regex-cache
    arr-diff --> arr-flatten
    braces --> expand-range
    braces --> preserve
    braces --> repeat-element
    expand-range --> fill-range
    fill-range --> is-number
    fill-range --> isobject
    fill-range --> randomatic
    fill-range --> repeat-element
    fill-range --> repeat-string
    is-number --> kind-of
    isobject --> isarray
    randomatic --> is-number
    randomatic --> kind-of
    randomatic --> math-random
    expand-brackets --> is-posix-bracket
    extglob --> is-extglob
    is-glob --> is-extglob
    normalize-path --> remove-trailing-separator
    object.omit --> for-own
    object.omit --> is-extendable
    for-own --> for-in
    parse-glob --> glob-base
    parse-glob --> is-dotfile
    parse-glob --> is-extglob
    parse-glob --> is-glob
    glob-base --> glob-parent
    glob-base --> is-glob
    glob-parent --> is-glob
    regex-cache --> is-equal-shallow
    is-equal-shallow --> is-primitive
    is-binary-path --> binary-extensions
    readdirp --> graceful-fs
    readdirp --> minimatch
    readdirp --> readable-stream
    readdirp --> set-immediate-shim
    findup-sync --> detect-file
    findup-sync --> is-glob
    findup-sync --> micromatch
    findup-sync --> resolve-dir
    detect-file --> fs-exists-sync
    resolve-dir --> expand-tilde
    resolve-dir --> global-modules
    expand-tilde --> os-homedir
    global-modules --> global-prefix
    global-modules --> is-windows
    global-prefix --> homedir-polyfill
    global-prefix --> ini
    global-prefix --> is-windows
    global-prefix --> which
    homedir-polyfill --> parse-passwd
    walk-sync --> ensure-posix-path
    walk-sync --> matcher-collection
    matcher-collection --> minimatch
    sauce-tunnel --> chalk
    sauce-tunnel --> request
    sauce-tunnel --> split
    uglify-js --> async
    uglify-js --> source-map
    uglify-js --> uglify-to-browserify
    uglify-js --> yargs
    webpack --> acorn
    webpack --> async
    webpack --> clone
    webpack --> enhanced-resolve
    webpack --> interpret
    webpack --> loader-utils
    webpack --> memory-fs
    webpack --> mkdirp
    webpack --> node-libs-browser
    webpack --> optimist
    webpack --> supports-color
    webpack --> tapable
    webpack --> uglify-js
    webpack --> watchpack
    webpack --> webpack-core
    enhanced-resolve --> graceful-fs
    enhanced-resolve --> memory-fs
    enhanced-resolve --> tapable
    memory-fs --> errno
    memory-fs --> readable-stream
    errno --> prr
    loader-utils --> big.js
    loader-utils --> emojis-list
    loader-utils --> json5
    loader-utils --> object-assign
    node-libs-browser --> assert
    node-libs-browser --> browserify-zlib
    node-libs-browser --> buffer
    node-libs-browser --> console-browserify
    node-libs-browser --> constants-browserify
    node-libs-browser --> crypto-browserify
    node-libs-browser --> domain-browser
    node-libs-browser --> events
    node-libs-browser --> https-browserify
    node-libs-browser --> os-browserify
    node-libs-browser --> path-browserify
    node-libs-browser --> process
    node-libs-browser --> punycode
    node-libs-browser --> querystring-es3
    node-libs-browser --> readable-stream
    node-libs-browser --> stream-browserify
    node-libs-browser --> stream-http
    node-libs-browser --> string_decoder
    node-libs-browser --> timers-browserify
    node-libs-browser --> tty-browserify
    node-libs-browser --> url
    node-libs-browser --> util
    node-libs-browser --> vm-browserify
    assert --> util
    util --> inherits
    browserify-zlib --> pako
    buffer --> base64-js
    buffer --> ieee754
    buffer --> isarray
    console-browserify --> date-now
    crypto-browserify --> browserify-aes
    crypto-browserify --> pbkdf2-compat
    crypto-browserify --> ripemd160
    crypto-browserify --> sha.js
    browserify-aes --> inherits
    stream-browserify --> inherits
    stream-browserify --> readable-stream
    stream-http --> builtin-status-codes
    stream-http --> inherits
    stream-http --> readable-stream
    stream-http --> to-arraybuffer
    stream-http --> xtend
    timers-browserify --> setimmediate
    url --> punycode
    url --> querystring
    vm-browserify --> indexof
    watchpack --> async
    watchpack --> chokidar
    watchpack --> graceful-fs
    webpack-core --> source-list-map
    webpack-core --> source-map