graph TD
    request --> qs
    request --> aws4
    request --> uuid
    request --> extend
    request --> caseless
    request --> isstream
    request --> aws-sign2
    request --> form-data
    request --> mime-types
    request --> oauth-sign
    request --> safe-buffer
    request --> tough-cookie
    request --> tunnel-agent
    request --> forever-agent
    request --> har-validator
    request --> is-typedarray
    request --> http-signature
    request --> combined-stream
    request --> performance-now
    request --> json-stringify-safe
    qs --> side-channel
    side-channel --> call-bind
    side-channel --> es-errors
    side-channel --> get-intrinsic
    side-channel --> object-inspect
    call-bind --> es-define-property
    call-bind --> es-errors
    call-bind --> function-bind
    call-bind --> get-intrinsic
    call-bind --> set-function-length
    es-define-property --> get-intrinsic
    get-intrinsic --> es-errors
    get-intrinsic --> function-bind
    get-intrinsic --> has-proto
    get-intrinsic --> has-symbols
    get-intrinsic --> hasown
    hasown --> function-bind
    set-function-length --> define-data-property
    set-function-length --> es-errors
    set-function-length --> function-bind
    set-function-length --> get-intrinsic
    set-function-length --> gopd
    set-function-length --> has-property-descriptors
    define-data-property --> es-define-property
    define-data-property --> es-errors
    define-data-property --> gopd
    gopd --> get-intrinsic
    has-property-descriptors --> es-define-property
    form-data --> asynckit
    form-data --> combined-stream
    form-data --> mime-types
    combined-stream --> delayed-stream
    mime-types --> mime-db
    tough-cookie --> tldts
    tldts --> tldts-core
    tunnel-agent --> safe-buffer
    har-validator --> ajv
    har-validator --> har-schema
    ajv --> fast-deep-equal
    ajv --> fast-uri
    ajv --> json-schema-traverse
    ajv --> require-from-string
    http-signature --> assert-plus
    http-signature --> jsprim
    http-signature --> sshpk
    jsprim --> assert-plus
    jsprim --> extsprintf
    jsprim --> json-schema
    jsprim --> verror
    verror --> assert-plus
    verror --> core-util-is
    verror --> extsprintf
    sshpk --> asn1
    sshpk --> assert-plus
    sshpk --> dashdash
    sshpk --> getpass
    sshpk --> safer-buffer
    sshpk --> jsbn
    sshpk --> tweetnacl
    sshpk --> ecc-jsbn
    sshpk --> bcrypt-pbkdf
    asn1 --> safer-buffer
    dashdash --> assert-plus
    getpass --> assert-plus
    ecc-jsbn --> jsbn
    bcrypt-pbkdf --> tweetnacl